spring:
  datasource:
    url: jdbc:sqlserver://10.26.231.210;database=YG_MES
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ride
    password: ABCabc123#


logging:
  level:
    com.hfmes.sunshine: debug
mybatis:
  type-aliases-package: com.hfmes.sunshine.domain
  mapper-locations: classpath:mapper/*.xml

  # 打开延迟加载的开关，再将积极加载改为消极加载（即按需加载）
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false